package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * Goannotation generated by hbm2java
 */
public class Goannotation implements java.io.Serializable {

	private Integer id;
	private Proteins proteins;
	private String category;
	private String title;
	private String goid;
	private String evidenceQualifier;

	public Goannotation() {
	}

	public Goannotation(Proteins proteins, String goid) {
		this.proteins = proteins;
		this.goid = goid;
	}

	public Goannotation(Proteins proteins, String category, String title,
			String goid, String evidenceQualifier) {
		this.proteins = proteins;
		this.category = category;
		this.title = title;
		this.goid = goid;
		this.evidenceQualifier = evidenceQualifier;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Proteins getProteins() {
		return this.proteins;
	}

	public void setProteins(Proteins proteins) {
		this.proteins = proteins;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getGoid() {
		return this.goid;
	}

	public void setGoid(String goid) {
		this.goid = goid;
	}

	public String getEvidenceQualifier() {
		return this.evidenceQualifier;
	}

	public void setEvidenceQualifier(String evidenceQualifier) {
		this.evidenceQualifier = evidenceQualifier;
	}

}
