package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * InteractionConfscore generated by hbm2java
 */
public class InteractionConfscore implements java.io.Serializable {

	private Integer intconfid;
	private Interaction interaction;
	private String type;
	private String value;

	public InteractionConfscore() {
	}

	public InteractionConfscore(Interaction interaction, String type,
			String value) {
		this.interaction = interaction;
		this.type = type;
		this.value = value;
	}

	public Integer getIntconfid() {
		return this.intconfid;
	}

	public void setIntconfid(Integer intconfid) {
		this.intconfid = intconfid;
	}

	public Interaction getInteraction() {
		return this.interaction;
	}

	public void setInteraction(Interaction interaction) {
		this.interaction = interaction;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
