package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * Method generated by hbm2java
 */
public class Method implements java.io.Serializable {

	private Integer id;
	private Interaction interaction;
	private String name;

	public Method() {
	}

	public Method(Interaction interaction, String name) {
		this.interaction = interaction;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Interaction getInteraction() {
		return this.interaction;
	}

	public void setInteraction(Interaction interaction) {
		this.interaction = interaction;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
