package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * Metname generated by hbm2java
 */
public class Metname implements java.io.Serializable {

	private Integer id;
	private Pubmedref pubmedref;
	private String shortLabel;
	private String fullName;
	private String miontology;
	private Integer oldId;

	public Metname() {
	}

	public Metname(Pubmedref pubmedref) {
		this.pubmedref = pubmedref;
	}

	public Metname(Pubmedref pubmedref, String shortLabel, String fullName,
			String miontology, Integer oldId) {
		this.pubmedref = pubmedref;
		this.shortLabel = shortLabel;
		this.fullName = fullName;
		this.miontology = miontology;
		this.oldId = oldId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Pubmedref getPubmedref() {
		return this.pubmedref;
	}

	public void setPubmedref(Pubmedref pubmedref) {
		this.pubmedref = pubmedref;
	}

	public String getShortLabel() {
		return this.shortLabel;
	}

	public void setShortLabel(String shortLabel) {
		this.shortLabel = shortLabel;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getMiontology() {
		return this.miontology;
	}

	public void setMiontology(String miontology) {
		this.miontology = miontology;
	}

	public Integer getOldId() {
		return this.oldId;
	}

	public void setOldId(Integer oldId) {
		this.oldId = oldId;
	}

}
