package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Pathway generated by hbm2java
 */
public class Pathway implements java.io.Serializable {

	private Integer id;
	private String pathName;
	private String pathDes;
	private Integer oldId;
	private Set protToPaths = new HashSet(0);

	public Pathway() {
	}

	public Pathway(String pathName) {
		this.pathName = pathName;
	}

	public Pathway(String pathName, String pathDes, Integer oldId,
			Set protToPaths) {
		this.pathName = pathName;
		this.pathDes = pathDes;
		this.oldId = oldId;
		this.protToPaths = protToPaths;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPathName() {
		return this.pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}

	public String getPathDes() {
		return this.pathDes;
	}

	public void setPathDes(String pathDes) {
		this.pathDes = pathDes;
	}

	public Integer getOldId() {
		return this.oldId;
	}

	public void setOldId(Integer oldId) {
		this.oldId = oldId;
	}

	public Set getProtToPaths() {
		return this.protToPaths;
	}

	public void setProtToPaths(Set protToPaths) {
		this.protToPaths = protToPaths;
	}

}
