package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * Proteinsource generated by hbm2java
 */
public class Proteinsource implements java.io.Serializable {

	private Integer id;
	private Proteins proteins;
	private String name;

	public Proteinsource() {
	}

	public Proteinsource(Proteins proteins, String name) {
		this.proteins = proteins;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Proteins getProteins() {
		return this.proteins;
	}

	public void setProteins(Proteins proteins) {
		this.proteins = proteins;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
