package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * Proteinsalias generated by hbm2java
 */
public class Proteinsalias implements java.io.Serializable {

	private Integer id;
	private Proteins proteins;
	private String type;
	private String alias;

	public Proteinsalias() {
	}

	public Proteinsalias(Proteins proteins, String type, String alias) {
		this.proteins = proteins;
		this.type = type;
		this.alias = alias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Proteins getProteins() {
		return this.proteins;
	}

	public void setProteins(Proteins proteins) {
		this.proteins = proteins;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

}
