package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Proteins generated by hbm2java
 */
public class Proteins implements java.io.Serializable {

	private Integer prid;
	private String entrezgeneid;
	private String genesymbol;
	private String description;
	private Set protToPaths = new HashSet(0);
	private Set proteinDrugs = new HashSet(0);
	private Set goannotations = new HashSet(0);
	private Set proteinsaliases = new HashSet(0);
	private Set proteinsources = new HashSet(0);
	private Set interactionsForPridB = new HashSet(0);
	private Set screens = new HashSet(0);
	private Set interactionsForPridA = new HashSet(0);
	private Set expressions = new HashSet(0);

	public Proteins() {
	}

	public Proteins(String entrezgeneid, String genesymbol, String description,
			Set protToPaths, Set proteinDrugs, Set goannotations,
			Set proteinsaliases, Set proteinsources, Set interactionsForPridB,
			Set screens, Set interactionsForPridA, Set expressions) {
		this.entrezgeneid = entrezgeneid;
		this.genesymbol = genesymbol;
		this.description = description;
		this.protToPaths = protToPaths;
		this.proteinDrugs = proteinDrugs;
		this.goannotations = goannotations;
		this.proteinsaliases = proteinsaliases;
		this.proteinsources = proteinsources;
		this.interactionsForPridB = interactionsForPridB;
		this.screens = screens;
		this.interactionsForPridA = interactionsForPridA;
		this.expressions = expressions;
	}

	public Integer getPrid() {
		return this.prid;
	}

	public void setPrid(Integer prid) {
		this.prid = prid;
	}

	public String getEntrezgeneid() {
		return this.entrezgeneid;
	}

	public void setEntrezgeneid(String entrezgeneid) {
		this.entrezgeneid = entrezgeneid;
	}

	public String getGenesymbol() {
		return this.genesymbol;
	}

	public void setGenesymbol(String genesymbol) {
		this.genesymbol = genesymbol;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getProtToPaths() {
		return this.protToPaths;
	}

	public void setProtToPaths(Set protToPaths) {
		this.protToPaths = protToPaths;
	}

	public Set getProteinDrugs() {
		return this.proteinDrugs;
	}

	public void setProteinDrugs(Set proteinDrugs) {
		this.proteinDrugs = proteinDrugs;
	}

	public Set getGoannotations() {
		return this.goannotations;
	}

	public void setGoannotations(Set goannotations) {
		this.goannotations = goannotations;
	}

	public Set getProteinsaliases() {
		return this.proteinsaliases;
	}

	public void setProteinsaliases(Set proteinsaliases) {
		this.proteinsaliases = proteinsaliases;
	}

	public Set getProteinsources() {
		return this.proteinsources;
	}

	public void setProteinsources(Set proteinsources) {
		this.proteinsources = proteinsources;
	}

	public Set getInteractionsForPridB() {
		return this.interactionsForPridB;
	}

	public void setInteractionsForPridB(Set interactionsForPridB) {
		this.interactionsForPridB = interactionsForPridB;
	}

	public Set getScreens() {
		return this.screens;
	}

	public void setScreens(Set screens) {
		this.screens = screens;
	}

	public Set getInteractionsForPridA() {
		return this.interactionsForPridA;
	}

	public void setInteractionsForPridA(Set interactionsForPridA) {
		this.interactionsForPridA = interactionsForPridA;
	}

	public Set getExpressions() {
		return this.expressions;
	}

	public void setExpressions(Set expressions) {
		this.expressions = expressions;
	}

}
