package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * ProteinDrug generated by hbm2java
 */
public class ProteinDrug implements java.io.Serializable {

	private Integer id;
	private Proteins proteins;
	private String drugbankid;
	private String name;
	private String moa;

	public ProteinDrug() {
	}

	public ProteinDrug(Proteins proteins, String drugbankid) {
		this.proteins = proteins;
		this.drugbankid = drugbankid;
	}

	public ProteinDrug(Proteins proteins, String drugbankid, String name,
			String moa) {
		this.proteins = proteins;
		this.drugbankid = drugbankid;
		this.name = name;
		this.moa = moa;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Proteins getProteins() {
		return this.proteins;
	}

	public void setProteins(Proteins proteins) {
		this.proteins = proteins;
	}

	public String getDrugbankid() {
		return this.drugbankid;
	}

	public void setDrugbankid(String drugbankid) {
		this.drugbankid = drugbankid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMoa() {
		return this.moa;
	}

	public void setMoa(String moa) {
		this.moa = moa;
	}

}
