package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * ProtToPath generated by hbm2java
 */
public class ProtToPath implements java.io.Serializable {

	private Integer id;
	private Proteins proteins;
	private Pathway pathway;

	public ProtToPath() {
	}

	public ProtToPath(Proteins proteins, Pathway pathway) {
		this.proteins = proteins;
		this.pathway = pathway;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Proteins getProteins() {
		return this.proteins;
	}

	public void setProteins(Proteins proteins) {
		this.proteins = proteins;
	}

	public Pathway getPathway() {
		return this.pathway;
	}

	public void setPathway(Pathway pathway) {
		this.pathway = pathway;
	}

}
