package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Pubmedref generated by hbm2java
 */
public class Pubmedref implements java.io.Serializable {

	private Integer id;
	private Interaction interaction;
	private Integer pubmedid;
	private String experimentalScale;
	private Integer oldId;
	private Set metnames = new HashSet(0);

	public Pubmedref() {
	}

	public Pubmedref(Interaction interaction) {
		this.interaction = interaction;
	}

	public Pubmedref(Interaction interaction, Integer pubmedid,
			String experimentalScale, Integer oldId, Set metnames) {
		this.interaction = interaction;
		this.pubmedid = pubmedid;
		this.experimentalScale = experimentalScale;
		this.oldId = oldId;
		this.metnames = metnames;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Interaction getInteraction() {
		return this.interaction;
	}

	public void setInteraction(Interaction interaction) {
		this.interaction = interaction;
	}

	public Integer getPubmedid() {
		return this.pubmedid;
	}

	public void setPubmedid(Integer pubmedid) {
		this.pubmedid = pubmedid;
	}

	public String getExperimentalScale() {
		return this.experimentalScale;
	}

	public void setExperimentalScale(String experimentalScale) {
		this.experimentalScale = experimentalScale;
	}

	public Integer getOldId() {
		return this.oldId;
	}

	public void setOldId(Integer oldId) {
		this.oldId = oldId;
	}

	public Set getMetnames() {
		return this.metnames;
	}

	public void setMetnames(Set metnames) {
		this.metnames = metnames;
	}

}
