package databaseAccess;

// Generated 1/Jul/2015 12:11:11 by Hibernate Tools 4.0.0

/**
 * Screen generated by hbm2java
 */
public class Screen implements java.io.Serializable {

	private Integer id;
	private Proteins proteins;
	private String source;

	public Screen() {
	}

	public Screen(Proteins proteins, String source) {
		this.proteins = proteins;
		this.source = source;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Proteins getProteins() {
		return this.proteins;
	}

	public void setProteins(Proteins proteins) {
		this.proteins = proteins;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

}
